services:
  db:
    image: postgres:16
    container_name: app4something-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app4something
    ports:
      - "5432:5432"
    volumes:
      - app4something_pg:/var/lib/postgresql/data

volumes:
  app4something_pg:
